language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore src

script:
 - dotnet build src
 - dotnet test src/Gg.Scottie.Dotnet.Standard.Testing.Unit.Tests/Gg.Scottie.Dotnet.Standard.Testing.Unit.Tests.csproj
